version: '3.7'

services:
  backend:
    build :
     context: ./java/backendapi/simple-api-student-main/
     dockerfile : Dockerfile
    networks:
      - app-network
    depends_on:
    - database


  database:
    build:
      context : ./postgres/
      dockerfile: Dockerfile
    volumes:
      - ./postgres/db-data:/var/lib/postgresql/data:rw
    networks:
      - app-network

  httpd:
    build:
      context : ./http/
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    name: app-network
    external: true