# This is the Github Actions workflow configuration for CI/CD
name: CI devops 2023

# Specifying the events that trigger the workflow
on:
  # The workflow will run when a push event occurs on the "main" branch
  # or when a pull request is opened
  push:
    branches: main
  pull_request:

# Defining the jobs that will run as part of the workflow
jobs:
  # Job to test the backend application
  test-backend:
    # The job will run on an Ubuntu 22.04 runner
    runs-on: ubuntu-22.04
    steps:
      # Checkout the code from the Github repository
      - uses: actions/checkout@v2.5.0

      # Set up Java version 17 with the "actions/setup-java" action
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "adopt"

      # Build the backend application using Maven and run sonar scans on the code
      - name: Build and test with Maven
        run: cd ./java/backendapi/simple-api-student-main/ && mvn -B -X verify sonar:sonar -Dsonar.projectKey=julien-odet-cpe_DevOps-ODET-PERRAUD -Dsonar.organization=devops-2023-odet-perraud -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./pom.xml

  # Job to build and push the docker images
  build-and-push-docker-image:
    # This job requires the "test-backend" job to complete successfully
    needs: test-backend
    # The job will run on an Ubuntu 22.04 runner
    runs-on: ubuntu-22.04

    # Steps to perform in the job
    steps:
      # Checkout the code from the Github repository
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Login to DockerHub using the Docker login and password stored as secrets
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the "simple-api" docker image
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          # The relative path to the location of the source code with the Dockerfile
          context: ./java/backendapi/simple-api-student-main
          # The tags for the image, which must be all lower-case
          tags: ${{secrets.DOCKER_LOGIN}}/simple-api
          # Only push the image if the Github ref event is a push to the main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      # Build and push the "database" docker image
      - name: Build image database
        uses: docker/build-push-action@v3
