name: CI devops 2023
on:
  #to begin you want to launch this job in main and develop
  push:
    branches: main
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      #checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            java-version: 17
            distribution: "adopt"
    #finally build your app with the latest command
      - name: Build and test with Maven
        run: cd ./java/backendapi/simple-api-student-main/ && mvn -B verify sonar:sonar -Dsonar.projectKey=julien-odet-cpe_DevOps-ODET-PERRAUD -Dsonar.organization=devops-2023-odet-perraud -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}  --file ./pom.xml
  # define job to build and publish docker image
  build-and-push-docker-image:
    needs: test-backend
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-22.04

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}
               
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./java/backendapi/simple-api-student-main
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_LOGIN}}/simple-api
          push: ${{ github.ref == 'refs/heads/main' }}


      - name: Build image database
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./postgres
          #Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_LOGIN}}/database
          push: ${{ github.ref == 'refs/heads/main' }}



      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./http
          # Note: tags has to be all lower-case
          tags: ${{secrets.DOCKER_LOGIN}}/http
          push: ${{ github.ref == 'refs/heads/main' }}

        # DO the same for httpd

